---
# check.yml
# check which program to use for finding check_suid_sgid_list_of_files

- name: check dnf command
  stat:
    path: "{{ item }}/dnf"
  loop:
    - "/usr/bin"
    - "/usr/sbin"
    - "/bin"
    - "/sbin"
  register: check_suid_sgid_dnf_exist
  ignore_errors: yes

- debug:
    msg: "{{ check_suid_sgid_dnf_exist.results }}"
  when: check_suid_sgid_debug_messages

- name: check rpm command
  stat:
    path: "{{ item }}/rpm"
  register: check_suid_sgid_rpm_exist
  ignore_errors: yes
  loop:
     - /usr/bin
     - /usr/sbin
     - /bin
     - /sbin

- debug:
    msg: "{{ check_suid_sgid_rpm_exist.results }}"
  when: check_suid_sgid_debug_messages

- name: select query command dnf
  set_fact:
    check_suid_sgid_command_to_query_packages: "{{ check_suid_sgid_command_dnf_query }}"
  when: "{{ item.stat.exists }}" #check_suid_sgid_dnf_exist.exists
  loop: "{{ check_suid_sgid_dnf_exist.results }}"

- name: select query command rpm
  set_fact:
    check_suid_sgid_command_to_query_packages: "{{ check_suid_sgid_command_rpm_query }}"
  when: "{{ item.stat.exists }}" # check_suid_sgid_rpm_exist.rc == 1
  loop: "{{ check_suid_sgid_rpm_exist.results }}"

- debug:
    msg: "query command selected: {{ check_suid_sgid_command_to_query_packages }}"
