---
# Role tasks

- name: setup dependency packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ check_suid_sgid_dependency_packages }}"

- name: search suid/sgid programs
  shell: >-
    find /
    \(
    -path
    {{ check_suid_sgid_excluded_dirs
       | join(" -prune -o -path ")
    }}
    \)
    -prune
    -o
    \( -perm -4000 -or -perm -2000 \)
    -print
  changed_when: false
  register: check_suid_sgid_search_result

- name: search packages owning suid/sgid files
  shell: "rpm -qf --queryformat '%{NAME}' {{ item }}"
  args:
    warn: false
  failed_when: false
  changed_when: false
  when:
  register: check_suid_sgid_search_packages_result
  loop: >-
    {{ check_suid_sgid_search_result.stdout_lines
       | reject('search','^/proc')
       | reject('search','^/run')
       | reject('search','^/sys')
       | list }}

- name: setup facts with packages/files with suid/sgid
  set_fact:
    check_suid_sgid_packages_found: >-
      {{ check_suid_sgid_search_packages_result.results
         | selectattr("rc", "equalto", 0)
         | map(attribute="stdout")
         | list
         | sort
         | unique }}
    check_suid_sgid_files_found: >-
      {{ check_suid_sgid_search_packages_result.results
         | selectattr("rc", "greaterthan", 0)
         | map(attribute="item")
         | list
         | sort
         | unique }}

- name: remove packages with suid/sgid files
  package:
    name: "{{ item }}"
    state: absent
  when:
    - item not in check_suid_sgid_excluded_packages
    - check_suid_sgid_packages_state == "absent"
  loop: "{{ check_suid_sgid_packages_found }}"

- name: remove files with suid/sgid files
  file:
    path: "{{ item }}"
    state: "{{ check_suid_sgid_files_state }}"
  when:
    - item not in check_suid_sgid_excluded_files
    - check_suid_sgid_files_state == "absent"
  loop: "{{ check_suid_sgid_files_found }}"
