---
# Role tasks

- include: find.yml

- name: search of packages for files with rpm
  shell: "rpm -qf {{ item }}"
  register:  rpm_output
  loop: "{{ list_of_files }}"
  changed_when: false

- debug:
    msg: "file: {{ item.item }} --> package: {{ item.stdout }}"
  loop: "{{ rpm_output.results }}"
