---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Install a package that have a suid/sgid file
      ansible.builtin.package:
        name: screen
        state: present
      when: >-
        not ( ansible_facts['distribution'] == 'CentOS'
        and ansible_facts['distribution_major_version'] == '8')

    - name: Create a suid file
      ansible.builtin.copy:
        dest: /tmp/suid_file
        content: Hello World
        mode: 04000

    - name: Create a sgid file
      ansible.builtin.copy:
        dest: /tmp/suid_file
        content: Hello World
        mode: 02000
