---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check for suid/sgid test package
      ansible.builtin.command: rpm -q screen
      args:
        warn: no
      changed_when: no
      failed_when: no
      register: check_package_result

    - name: Check for suid test file
      ansible.builtin.stat:
        path: /tmp/suid_file
      register: check_suid_file_result

    - name: Check for sgid test file
      ansible.builtin.stat:
        path: /tmp/sgid_file
      register: check_sgid_file_result

    - name: Verify that role removed package/files with suid/sgid
      ansible.builtin.assert:
        that:
          - check_package_result.rc != 0
          - not check_suid_file_result.stat.exists
          - not check_sgid_file_result.stat.exists
